# Generated by Django 3.0.1 on 2020-01-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resource_userresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
