# Generated by Django 3.0.1 on 2020-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200105_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresource',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
