# Generated by Django 3.0.1 on 2020-02-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='Link',
        ),
    ]
